### ISSUE TITLE
DatabaseException['not authorized for query on heroku_appxxx.xxx' (code = 16550)]

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#109]
Hi, i'm using ReactiveMongo with play plugin on heroku, mongo served by mongolab.com (starter) mongod 2.4.5-rc0

On startup or wake-up of my machine/app I regularly have a lot of database exceptions like the one posted below. Once the app is running I'm not seeing them any more.

I would be surprised that during startup the mongolab server is rejecting authentication so I suspect a bug in the reactivemongo code?

I'm also seeing this error on my CI builds on cloudbees jenkins. One in two times some integration test fails with the same error.

Are there any configuration settings I can try to get rid if these issues?

the code of my app is available here:
https://github.com/francisdb/belgiantv

```
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_appxxx.xxx' (code = 16550)]
        at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32)
        at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:263)
        at reactivemongo.core.protocol.Response.error(protocol.scala:258)
        at reactivemongo.core.actors.MongoDBSystem$$anonfun$receive$1.applyOrElse(actors.scala:316)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
        at akka.actor.ActorCell.invoke(ActorCell.scala:386)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
        at akka.dispatch.Mailbox.run(Mailbox.scala:212)
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

**Comment by francisdb** [comment]
@tdrozdowski got a pointer to that pull request? Still seeing this issue...

**Comment by Otann** [comment]
Have same issue too on 0.10.5.0.akka23

**Comment by mrkaspa** [comment]
Same issue using reactive mongo val reactiveMongoV = "0.10.5.0.akka23"

**Comment by cchantep** [comment]
As the initial issue has been fixed, I think it would be better to ask for auth question on the [Google Group](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).

**Comment by jamesallchin** [comment]
Yes I have the same issue - 0.10.5.0.akka23 - mongolab on heroku

**Comment by francisdb** [comment]
still seeing this when my heroku app wakes up (0.11.2.play24)

```java
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app4877663.broadcasts' (code = 13)]
        at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32)
        at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:270)
        at reactivemongo.core.protocol.Response.error(protocol.scala:265)
        at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:479)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at reactivemongo.core.actors.LegacyDBSystem.aroundReceive(actors.scala:744)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ticofab** [comment]
This has started happening to me as well - using MongoLAB and reactive mongo play 0.11.7.play24. Any hints?

**Comment by cchantep** [comment]
Guys please check the mailinglist first.

**Comment by ticofab** [comment]
Done - and found the solution: adding `?authMode=scram-sha1` at the end of the mongodb uri. Pasting it here for reference. Thanks.

**Comment by mrkaspa** [comment]
Great

**Comment by maprohu** [comment]
Hi,

I had a similar problem with using reactivemongo with MongoLab on Heroku. The `authMode` option indeed solved half of the problem. However I was still experiencing authentication problems especially when I was connecting to the remote mongodb on Heroku from my pc.  What I noticed is that the authentication fails most of the time, but not always. 
Adding a `Thread.sleep(3000)` after connecting with `MongoDriver().connection(...)` seems to have solved the issue. So I guess the problem is when I try to access the database before some asynchronous authentication process is finished. Instead of adding a fixed delay I ended up waiting on the future returned by `connection.authenticate(dbname, auth, passwd)`, which also seems to work so far.

I am using reactivemongo version 0.11.7 with mondodb 3.0.7 on Heroku

**Comment by francisdb** [comment]
see https://groups.google.com/forum/#!topic/reactivemongo/x3OZ6-hIIXk

> Thanks, you can try MongoConnection.database (instead of MongoConnection.db or MongoConnection.apply) with a the 0.12.0-SNAPSHOT.
> This should at least wait for nodeset to be available (should be improve to wait for the primary, according the current readpref/write concern).

**Comment by ticofab** [comment]
There is an unanswered question on the mailing list: what is the way to go about this when using the Play plugin, until a new version is published to maven? Thanks.
